In [1]:
import numpy as np 
import pandas as pd

In [5]:
df=pd.read_csv("weather_data.csv")

In [9]:
print("original data is ")
df

original data is

         Day  Temperature  Humidity  Wind Speed
0     Monday           25        60          15
1    Tuesday           28        55          10
2  Wednesday           30        50          20
3   Thursday           22        70          10
4     Friday           26        65           8
5   Saturday           27        60           5
6     Sunday           24        75          12

In [39]:

#checking null values 
df.isna().sum()

Day              0
Temperature      0
Humidity         0
Wind Speed       0
comfort_score    0
dtype: int64

In [23]:
print(df.columns)

Index(['Day', 'Temperature', 'Humidity', 'Wind Speed'], dtype='object')

In [25]:
df["comfort_score"]=df['Temperature'] * 0.4 + df['Humidity'] * 0.4 + df['Wind Speed'] * 0.2

In [27]:
print("data with comfort score")
df

data with comfort score

         Day  Temperature  Humidity  Wind Speed  comfort_score
0     Monday           25        60          15           37.0
1    Tuesday           28        55          10           35.2
2  Wednesday           30        50          20           36.0
3   Thursday           22        70          10           38.8
4     Friday           26        65           8           38.0
5   Saturday           27        60           5           35.8
6     Sunday           24        75          12           42.0

In [37]:
best_day = df.loc[df['comfort_score'].idxmin()]  
best_dayy = best_day['Day']
best_dayy

'Tuesday'

In [ ]:
print("tuesday is the best day to go outside based on the comfort score ")